name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t gweinert/udemy-docker-react-tutorial -f Dockerfile.dev .
      - run: docker run -e CI=true gweinert/react-test npm test

      - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: udemy-docker-react-tutorial
        environment_name: Udemydockerreacttutorial-env
        existing_bucket_name: elasticbeanstalk-us-west-2-431852956755
        region: us-west-2
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
